name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Deploy Bicep
      run: |
        az bicep install
        pwd
        ls -la
        ls -la infra/
        az deployment group create \
          --resource-group aguadamillas_students_1 \
          --template-file ./infra/main.bicep \
          --parameters @./infra/parameters.json